/** Languages offered on student/advisor signup (multi-select). */
export const SIGNUP_LANGUAGE_OPTIONS = [
  "Hindi",
  "English",
  "Bengali",
  "Telugu",
  "Marathi",
  "Tamil",
  "Gujarati",
  "Urdu",
  "Kannada",
  "Odia",
  "Malayalam",
  "Punjabi",
  "Assamese",
  "Maithili",
  "Santali",
  "Kashmiri",
  "Nepali",
  "Konkani",
  "Sindhi",
  "Dogri",
  "Manipuri (Meitei)",
  "Bodo",
  "Sanskrit",
  "Spanish",
  "French",
  "German",
  "Portuguese",
  "Russian",
  "Chinese (Mandarin)",
  "Japanese",
  "Korean",
  "Arabic",
  "Italian",
  "Dutch",
  "Turkish",
  "Persian (Farsi)",
  "Thai",
  "Vietnamese",
  "Indonesian",
  "Malay",
  "Swedish",
  "Polish",
  "Greek",
  "Hebrew",
  "Other",
] as const;

export const OTHER_LANGUAGE_LABEL = "Other";
