/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Advisor = IDL.Record({
  'branch' : IDL.Text,
  'name' : IDL.Text,
  'year' : IDL.Nat,
  'sessionPrice' : IDL.Nat,
  'rating' : IDL.Float64,
  'college' : IDL.Text,
});

export const idlService = IDL.Service({
  'addAdvisor' : IDL.Func([Advisor], [], []),
  'getAllAdvisors' : IDL.Func([], [IDL.Vec(Advisor)], ['query']),
  'initialize' : IDL.Func([], [], []),
  'searchByBranch' : IDL.Func([IDL.Text], [IDL.Vec(Advisor)], ['query']),
  'searchByCollege' : IDL.Func([IDL.Text], [IDL.Vec(Advisor)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Advisor = IDL.Record({
    'branch' : IDL.Text,
    'name' : IDL.Text,
    'year' : IDL.Nat,
    'sessionPrice' : IDL.Nat,
    'rating' : IDL.Float64,
    'college' : IDL.Text,
  });
  
  return IDL.Service({
    'addAdvisor' : IDL.Func([Advisor], [], []),
    'getAllAdvisors' : IDL.Func([], [IDL.Vec(Advisor)], ['query']),
    'initialize' : IDL.Func([], [], []),
    'searchByBranch' : IDL.Func([IDL.Text], [IDL.Vec(Advisor)], ['query']),
    'searchByCollege' : IDL.Func([IDL.Text], [IDL.Vec(Advisor)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };